[package]
name = "shared-types"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
postcard-bindgen = { version = "0.7.0", features = ["generating"] }
embedded-alloc = "0.6.0"
