[workspace]
resolver = "3"
members = [
    "firmware",
    "gen-bindings",
    "shared-types",
    "bootloader",
]
default-members = ["firmware"]


[profile.release]
debug = true
lto = true
opt-level = 's'
incremental = false
codegen-units = 1

[profile.dev]
debug = 2
lto = true
opt-level = "z"
